(function(){
'use strict';
const sb=window.sb;if(!sb?.rpc)return;const path=(location.pathname||'').toLowerCase();
function css(){if(document.getElementById('bingo-points-style'))return;const s=document.createElement('style');s.id='bingo-points-style';s.textContent=`.bingo-points-card{display:flex;align-items:center;gap:12px;padding:14px 16px;border-radius:16px;background:linear-gradient(135deg,#fff7e8,#fff);border:1px solid #f2d5ad;color:#0d2f77;box-shadow:0 8px 22px rgba(30,60,110,.06)}.bingo-points-coin{width:46px;height:46px;border-radius:50%;display:grid;place-items:center;background:#f59a23;color:#fff;font-weight:900;font-size:20px}.bingo-points-card b{font-size:22px}.bingo-points-card small{display:block;color:#7a8393;margin-top:2px}.bingo-points-earned{margin-top:14px;padding:14px;border-radius:14px;background:#fff7e8;border:1px solid #f2d5ad;color:#8b5200;font-weight:800;text-align:center}`;document.head.appendChild(s)}
async function summary(){try{const r=await sb.rpc('bingo_my_points_summary');if(r.error)throw r.error;return r.data||{balance:0}}catch(e){console.warn('BINGO Points unavailable',e);return null}}
async function injectOrders(){const host=document.querySelector('.orders');if(!host||document.getElementById('bingo-points-summary'))return;const d=await summary();if(!d)return;const el=document.createElement('div');el.id='bingo-points-summary';el.className='bingo-points-card';el.innerHTML=`<div class="bingo-points-coin">B</div><div><b>${Number(d.balance||0)} BINGO Points</b><small>رصيدك الحالي من مكافآت BINGO</small></div>`;const p=host.querySelector('p');p?.after(el)}
async function injectTracking(){const complete=document.getElementById('delivery-complete');if(!complete)return;const qs=new URLSearchParams(location.search),ref=(qs.get('delivery')||'').split('&')[0];if(!ref)return;try{const user=await window.BingoAuth?.getUser?.();if(!user)return;let q=sb.from('delivery_orders').select('id,status').eq('customer_id',user.id);q=/^[0-9a-f-]{36}$/i.test(ref)?q.eq('id',ref):q.eq('order_number',ref);const r=await q.limit(1);if(r.error||!r.data?.length)return;const o=r.data[0];if(o.status!=='delivered')return;const pr=await sb.rpc('bingo_order_points',{p_order_id:o.id});if(pr.error)return;let el=document.getElementById('bingo-points-earned');if(!el){el=document.createElement('div');el.id='bingo-points-earned';el.className='bingo-points-earned';complete.querySelector('.complete-card')?.appendChild(el)}const pts=Number(pr.data?.points||0);el.textContent=pts>0?`🎁 ربحت ${pts} BINGO Points من هذا الطلب`:'🎁 سيتم احتساب نقاط BINGO لهذا الطلب';}catch(e){console.warn('Order points unavailable',e)}}
function boot(){css();if(path.endsWith('/orders.html'))injectOrders();if(path.endsWith('/order-tracking.html')){setTimeout(injectTracking,1000);setInterval(injectTracking,10000)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();