window.BINGO_CONFIG={SUPABASE_URL:"https://ekjrizhsviftjiuumapg.supabase.co",SUPABASE_PUBLISHABLE_KEY:"sb_publishable_duAz3JsRhOyE1oyTlo69SA_R2n1OY84"};
(function(){
  function css(h){if(document.querySelector('link[href="'+h+'"]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href=h;document.head.appendChild(l);}
  function js(s,id){if(document.getElementById(id)||document.querySelector('script[src="'+s+'"]'))return;const x=document.createElement('script');x.id=id;x.src=s;x.defer=false;document.head.appendChild(x);}
  css('bingo-ui.css');
  css('release-mobile-v1.css?v=20260822-1');
  js('release-performance-v1.js?v=20260822-1','bingo-release-performance-loader');
  js('release-link-safety-v1.js?v=20260822-1','bingo-release-link-safety-loader');
  js('mobile-push.js?v=20260823-1','bingo-mobile-push-loader');
  if(/(?:^|\/)(?:bingo-delivery-seller|bingo-delivery-driver)\.html$/i.test(location.pathname)){css('bingo-delivery-modern-v1.css?v=20260822-1');css('bingo-delivery-modern-v2.css?v=20260822-1');js('bingo-delivery-modern-v2.js?v=20260822-1','bingo-delivery-modern-v2-loader');js('bingo-cancel-realtime-v1.js?v=20260823-1','bingo-cancel-realtime-loader');}
  if(/(?:^|\/)bingo-delivery-customer\.html$/i.test(location.pathname))js('bingo-customer-location-update-v2.js?v=20260822-2','bingo-customer-location-update-v2-loader');
  if(/(?:^|\/)order-tracking\.html$/i.test(location.pathname))js('bingo-order-tracking-location-v1.js?v=20260822-1','bingo-order-tracking-location-loader');
  if(/(?:^|\/)(?:orders|order-tracking)\.html$/i.test(location.pathname))js('bingo-customer-cancel-order-v1.js?v=20260823-1','bingo-customer-cancel-order-loader');
  if(/(?:^|\/)(?:erp|hr|admin)\.html$/i.test(location.pathname))js('bingo-page-i18n.js','bingo-page-i18n-loader');
  if(/(?:^|\/)admin\.html$/i.test(location.pathname)){js('admin-product-seller-link.js?v=20260820-1','admin-product-seller-link-loader');js('admin-listing-promotions.js?v=20260822-4','admin-listing-promotions-loader');js('admin-listing-performance.js?v=20260822-1','admin-listing-performance-loader');js('admin-manual-purchases.js?v=20260822-1','admin-manual-purchases-loader')}
  if(/(?:^|\/)marketplace\.html$/i.test(location.pathname))js('marketplace-promotions-zone.js?v=20260822-1','marketplace-promotions-zone-loader');
  if(/(?:^|\/)listing\.html$/i.test(location.pathname))js('listing-analytics.js?v=20260822-2','listing-analytics-loader');
  if(/(?:^|\/)dashboard\.html$/i.test(location.pathname))js('dashboard-listing-analytics.js?v=20260822-4','dashboard-listing-analytics-loader');
  if(/(?:^|\/)bingo-delivery-control\.html$/i.test(location.pathname)){js('bingo-order-units-v1.js?v=20260822-1','bingo-order-units-loader');js('bingo-admin-order-items-v1.js?v=20260822-1','bingo-admin-order-items-loader');js('bingo-admin-cancellations-v1.js?v=20260823-2','bingo-admin-cancellations-loader')}
  function addSummary(){if(!location.pathname.endsWith('bingo-delivery-admin.html'))return;const earnings=document.querySelector('#earnings');if(!earnings)return;let box=document.querySelector('#delivery-earnings-summary');if(!box){box=document.createElement('div');box.id='delivery-earnings-summary';box.style.cssText='display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:12px;margin:14px 0';const section=earnings.closest('.bd-card')||earnings.parentElement;if(!section?.parentNode)return;section.parentNode.insertBefore(box,section)}const totals={pending:0,approved:0,paid:0,total:0};[...earnings.querySelectorAll('tr')].forEach(tr=>{const cells=[...tr.children];if(cells.length<4)return;const status=(cells[3].textContent||'').trim().toLowerCase(),raw=(cells[2].textContent||'').replace(/[^0-9.\-]/g,''),amount=Number(raw||0);if(!Number.isFinite(amount))return;if(Object.prototype.hasOwnProperty.call(totals,status))totals[status]+=amount;totals.total+=amount});const signature=[totals.pending,totals.approved,totals.paid,totals.total].join('|');if(box.dataset.signature===signature)return;box.dataset.signature=signature;const card=(title,value,cls)=>`<div class="bd-card" style="margin:0"><div style="opacity:.7">${title}</div><div style="font-size:24px;font-weight:800" class="${cls||''}">${value.toFixed(3)} OMR</div></div>`;box.innerHTML=card('Pending',totals.pending,'warning')+card('Approved',totals.approved,'warning')+card('Paid',totals.paid,'success')+card('الإجمالي',totals.total,'')}
  document.addEventListener('DOMContentLoaded',()=>{if(!location.pathname.endsWith('bingo-delivery-admin.html'))return;let attempts=0;const timer=setInterval(()=>{addSummary();if(document.getElementById('earnings')||++attempts>=20)clearInterval(timer)},500);document.addEventListener('bingo:delivery-updated',addSummary)});
})();