window.BINGO_CONFIG={SUPABASE_URL:"https://ekjrizhsviftjiuumapg.supabase.co",SUPABASE_PUBLISHABLE_KEY:"sb_publishable_duAz3JsRhOyE1oyTlo69SA_R2n1OY84"};
(function(){
  function css(h){if(document.querySelector('link[href="'+h+'"]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href=h;document.head.appendChild(l);}
  function js(s,id){if(document.getElementById(id)||document.querySelector('script[src="'+s+'"]'))return;const x=document.createElement('script');x.id=id;x.src=s;x.defer=false;document.head.appendChild(x);}
  css('bingo-ui.css');css('release-mobile-v1.css?v=20260822-1');js('release-performance-v1.js?v=20260822-1','bingo-release-performance-loader');js('release-link-safety-v1.js?v=20260822-1','bingo-release-link-safety-loader');js('mobile-push.js?v=20260823-1','bingo-mobile-push-loader');
  if(/(?:^|\/)messages\.html$/i.test(location.pathname))js('message-push-dispatch.js?v=20260823-1','bingo-message-push-dispatch-loader');
  if(/(?:^|\/)(?:bingo-delivery-seller|bingo-delivery-driver)\.html$/i.test(location.pathname)){css('bingo-delivery-modern-v1.css?v=20260822-1');css('bingo-delivery-modern-v2.css?v=20260822-1');css('bingo-mobile-app-mode-v1.css?v=20260823-1');js('bingo-delivery-modern-v2.js?v=20260822-1','bingo-delivery-modern-v2-loader');js('bingo-cancel-realtime-v1.js?v=20260823-1','bingo-cancel-realtime-loader');js('bingo-mobile-app-mode-v1.js?v=20260823-1','bingo-mobile-app-mode-loader');js('bingo-mobile-role-router-v1.js?v=20260823-3','bingo-mobile-role-router-loader');}
  if(/(?:^|\/)bingo-delivery-customer\.html$/i.test(location.pathname))js('bingo-customer-location-update-v2.js?v=20260822-2','bingo-customer-location-update-v2-loader');
  if(/(?:^|\/)order-tracking\.html$/i.test(location.pathname))js('bingo-order-tracking-location-v1.js?v=20260822-1','bingo-order-tracking-location-loader');
  if(/(?:^|\/)(?:orders|order-tracking)\.html$/i.test(location.pathname)){js('bingo-customer-cancel-order-v1.js?v=20260823-1','bingo-customer-cancel-order-loader');js('bingo-customer-refund-status-v1.js?v=20260823-1','bingo-customer-refund-status-loader');}
  if(/(?:^|\/)(?:erp|hr|admin)\.html$/i.test(location.pathname))js('bingo-page-i18n.js','bingo-page-i18n-loader');
  if(/(?:^|\/)admin\.html$/i.test(location.pathname)){js('admin-product-seller-link.js?v=20260820-1','admin-product-seller-link-loader');js('admin-listing-promotions.js?v=20260822-4','admin-listing-promotions-loader');js('admin-listing-performance.js?v=20260822-1','bingo-admin-listing-performance-loader');js('admin-manual-purchases.js?v=20260822-1','admin-manual-purchases-loader');js('admin-app-roles-v1.js?v=20260823-1','admin-app-roles-loader')}
  if(/(?:^|\/)marketplace\.html$/i.test(location.pathname))js('marketplace-promotions-zone.js?v=20260822-1','bingo-marketplace-promotions-loader');
  if(/(?:^|\/)listing\.html$/i.test(location.pathname))js('listing-analytics.js?v=20260822-2','bingo-listing-analytics-loader');
  if(/(?:^|\/)dashboard\.html$/i.test(location.pathname))js('dashboard-listing-analytics.js?v=20260822-4','bingo-dashboard-listing-analytics-loader');
  if(/(?:^|\/)bingo-delivery-control\.html$/i.test(location.pathname)){js('bingo-order-units-v1.js?v=20260822-1','bingo-order-units-loader');js('bingo-admin-order-items-v1.js?v=20260822-1','bingo-admin-order-items-loader');js('bingo-admin-cancellations-v1.js?v=20260823-2','bingo-admin-cancellations-loader')}
})();