(function(){
'use strict';
const last=(location.pathname.split('/').pop()||'').toLowerCase();if(last&&last!=='index.html')return;
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const isAr=()=>((document.documentElement.lang||'').toLowerCase().startsWith('ar')||document.documentElement.dir==='rtl');
let offers=[];
function valid(a){const now=Date.now(),start=a.starts_at?new Date(a.starts_at).getTime():-Infinity,end=a.ends_at?new Date(a.ends_at).getTime():Infinity;return a&&a.image_url&&start<=now&&now<=end}
function mount(){if(document.querySelector('.bingo-featured-offers'))return;const near=document.querySelector('.bingo-nearby'),anchor=near||document.querySelector('.bingo-quick-wrap')||document.querySelector('.hero');if(!anchor)return;const sec=document.createElement('section');sec.className='bingo-featured-offers';sec.innerHTML='<div class="container"><div class="bfo-head"><div><span class="bfo-kicker" data-bfo="kicker"></span><h2 data-bfo="title"></h2><p data-bfo="desc"></p></div><div class="bfo-controls"><button type="button" id="bfoPrev" aria-label="Previous">‹</button><button type="button" id="bfoNext" aria-label="Next">›</button></div></div><div class="bfo-track" id="bfoTrack"><div class="bfo-skeleton"></div><div class="bfo-skeleton"></div><div class="bfo-skeleton"></div></div></div>';anchor.insertAdjacentElement('afterend',sec);document.getElementById('bfoPrev').onclick=()=>scrollOffers(-1);document.getElementById('bfoNext').onclick=()=>scrollOffers(1);applyLang();load()}
function scrollOffers(dir){const t=document.getElementById('bfoTrack');if(t)t.scrollBy({left:dir*(Math.min(t.clientWidth*.82,520)),behavior:'smooth'})}
async function load(){const track=document.getElementById('bfoTrack');if(!track||!window.sb?.from)return;try{const {data,error}=await window.sb.from('company_ads').select('id,title,image_url,link_url,sort_order,starts_at,ends_at,status,placement').eq('status','published').eq('placement','home_top').order('sort_order',{ascending:true}).limit(12);if(error)throw error;offers=(data||[]).filter(valid);render()}catch(e){console.warn('BINGO featured offers:',e);track.innerHTML='<div class="bfo-empty" data-bfo="unavailable"></div>';applyLang()}}
function render(){const track=document.getElementById('bfoTrack');if(!track)return;if(!offers.length){track.innerHTML='<div class="bfo-empty" data-bfo="empty"></div>';applyLang();return}track.innerHTML=offers.map((a,i)=>{const inner='<div class="bfo-media"><img src="'+esc(a.image_url)+'" alt="'+esc(a.title||'BINGO offer')+'" loading="lazy"><span class="bfo-badge" data-bfo-badge="1"></span></div><div class="bfo-copy"><strong>'+esc(a.title||'BINGO Offer')+'</strong><span data-bfo-view="1"></span></div>';return a.link_url?'<a class="bfo-card" href="'+esc(a.link_url)+'" target="_blank" rel="noopener noreferrer">'+inner+'</a>':'<article class="bfo-card">'+inner+'</article>'}).join('');applyLang()}
function applyLang(){const ar=isAr(),set=(sel,en,aa)=>{const el=document.querySelector(sel);if(el)el.textContent=ar?aa:en};set('[data-bfo="kicker"]','FEATURED OFFERS','عروض مميزة');set('[data-bfo="title"]','Offers worth discovering','عروض تستحق الاكتشاف');set('[data-bfo="desc"]','Selected offers from businesses on BINGO Oman.','عروض مختارة من الشركات على BINGO Oman.');set('[data-bfo="empty"]','No featured offers at the moment.','لا توجد عروض مميزة حاليًا.');set('[data-bfo="unavailable"]','Featured offers are temporarily unavailable.','تعذر تحميل العروض المميزة مؤقتًا.');document.querySelectorAll('[data-bfo-badge]').forEach(x=>x.textContent=ar?'مميز':'FEATURED');document.querySelectorAll('[data-bfo-view]').forEach(x=>x.textContent=ar?'اكتشف العرض ←':'Discover offer →')}
function watch(){new MutationObserver(applyLang).observe(document.documentElement,{attributes:true,attributeFilter:['lang','dir']});document.getElementById('langSwitch')?.addEventListener('click',()=>setTimeout(applyLang,60))}
function init(){mount();watch()}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();