(function(){
'use strict';
function asset(tag,type,url){if(document.querySelector('['+tag+']'))return;const e=document.createElement(type);if(type==='link'){e.rel='stylesheet';e.href=url}else{e.src=url;e.defer=true}e.setAttribute(tag,'1');document.head.appendChild(e)}
(function(){asset('data-bingo-responsive','link','responsive.css?v=20260819-1');asset('data-bingo-performance','link','performance.css?v=20260821-1');asset('data-bingo-performance-js','script','performance-loader.js?v=20260821-1')})();
(function(){const x=(location.pathname.split('/').pop()||'').toLowerCase();if(x==='admin.html'||x.startsWith('admin-'))return;asset('data-bingo-notifications','link','notifications.css?v=20260819-1');asset('data-bingo-notifications-js','script','notifications.js?v=20260819-1')})();
(function(){const x=(location.pathname.split('/').pop()||'').toLowerCase();if(x&&x!=='index.html')return;asset('data-bingo-oman-places','script','oman-places.js?v=20260819-2');asset('data-bingo-home-upgrade','link','bingo-home-upgrade.css?v=20260819-4');asset('data-bingo-home-responsive-final','link','home-responsive-final.css?v=20260819-1');asset('data-bingo-home-upgrade-js','script','bingo-home-upgrade.js?v=20260819-5');asset('data-bingo-featured-offers','link','featured-offers.css?v=20260819-1');asset('data-bingo-featured-offers-js','script','featured-offers.js?v=20260819-1')})();
(function(){const x=(location.pathname.split('/').pop()||'').toLowerCase();if(x==='add-listing.html'){asset('data-bingo-add-listing-upgrade','link','add-listing-upgrade.css?v=20260819-2');asset('data-bingo-add-listing-upgrade-js','script','add-listing-upgrade.js?v=20260819-2')}if(x==='marketplace.html')asset('data-bingo-marketplace-upgrade','link','marketplace-upgrade.css?v=20260819-2');if(x==='add-listing.html'||x==='marketplace.html')asset('data-bingo-category-loader','script','category-loader.js?v=20260821-1')})();
(function(){const x=(location.pathname.split('/').pop()||'').toLowerCase();if(x==='dashboard.html'||x==='messages.html')asset('data-bingo-account-messages-upgrade','link','account-messages-upgrade.css?v=20260819-1');if(x==='messages.html'){asset('data-bingo-messages-context','link','messages-context.css?v=20260821-1');asset('data-bingo-messages-context-js','script','messages-context.js?v=20260821-1')}if(x==='place.html')asset('data-bingo-place-hero-images','script','place-hero-images.js?v=20260819-1')})();
if(location.pathname.endsWith('/admin.html'))return;let items=[],index=0,timer=null;function esc(s){return String(s??'').replace(/[&<>\'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt',"'":'&#39;','\"':'&quot;'}[c]))}function resolveMediaUrl(value){const raw=String(value||'').trim();if(!raw)return'';if(/^https?:\/\//i.test(raw)||/^data:/i.test(raw)||raw.startsWith('blob:'))return raw;try{if(window.sb?.storage?.from){const path=raw.replace(/^\/+/, '').replace(/^bingo-banners\//,'');const {data}=window.sb.storage.from('bingo-banners').getPublicUrl(path);if(data?.publicUrl)return data.publicUrl}}catch(e){}return raw}function mount(){if(document.getElementById('bingoGlobalBannerWrap'))return document.getElementById('bingoGlobalBanner');const w=document.createElement('section');w.id='bingoGlobalBannerWrap';w.className='bingo-global-banner-wrap';w.innerHTML='<div id="bingoGlobalBanner" class="bingo-global-banner"></div>';const h=document.querySelector('header');h?h.insertAdjacentElement('afterend',w):document.body.insertAdjacentElement('afterbegin',w);return document.getElementById('bingoGlobalBanner')}function render(){const b=mount();clearInterval(timer);if(!items.length){b.innerHTML='';return}const a=items[index%items.length],u=resolveMediaUrl(a.media_url);if(!u){b.innerHTML='';return}const m=a.media_type==='video'?'<video class="bingo-global-media" src="'+esc(u)+'" autoplay muted loop playsinline preload="metadata"></video>':'<img class="bingo-global-media" src="'+esc(u)+'" alt="" loading="eager" decoding="async" fetchpriority="high">';b.innerHTML='<div class="bingo-global-slide active">'+(a.link_url?'<a class="bingo-global-link" href="'+esc(a.link_url)+'" target="_blank" rel="noopener noreferrer">'+m+'</a>':m)+'</div>';if(items.length>1)timer=setInterval(()=>{index=(index+1)%items.length;render()},6000);b.querySelector('video')?.play().catch(()=>{})}async function load(){mount();if(!window.sb?.from)return;try{const {data,error}=await sb.from('site_banners').select('id,media_type,media_url,link_url,sort_order,created_at,starts_at,ends_at,status').eq('status','published').order('sort_order',{ascending:true}).order('created_at',{ascending:false});if(error)throw error;const now=Date.now();items=(data||[]).filter(a=>(a.starts_at?new Date(a.starts_at).getTime():-Infinity)<=now&&(a.ends_at?new Date(a.ends_at).getTime():Infinity)>=now&&a.media_url);render()}catch(e){console.warn('BINGO global banners:',e)}}function init(){mount();load()}document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
})();