(function(){
  'use strict';
  (function loadResponsiveLayer(){if(document.querySelector('link[data-bingo-responsive]'))return;const link=document.createElement('link');link.rel='stylesheet';link.href='responsive.css?v=20260819-1';link.setAttribute('data-bingo-responsive','1');document.head.appendChild(link)})();
  (function loadNotifications(){const last=(location.pathname.split('/').pop()||'').toLowerCase();if(last==='admin.html'||last.startsWith('admin-'))return;if(!document.querySelector('link[data-bingo-notifications]')){const l=document.createElement('link');l.rel='stylesheet';l.href='notifications.css?v=20260819-1';l.setAttribute('data-bingo-notifications','1');document.head.appendChild(l)}if(!document.querySelector('script[data-bingo-notifications]')){const s=document.createElement('script');s.src='notifications.js?v=20260819-1';s.defer=true;s.setAttribute('data-bingo-notifications','1');document.head.appendChild(s)}})();
  (function loadOmanPlaces(){const last=(location.pathname.split('/').pop()||'').toLowerCase();if(last&&last!=='index.html')return;if(document.querySelector('script[data-bingo-oman-places]'))return;const script=document.createElement('script');script.src='oman-places.js?v=20260819-2';script.async=false;script.setAttribute('data-bingo-oman-places','1');document.head.appendChild(script)})();
  (function loadHomeUpgrade(){const last=(location.pathname.split('/').pop()||'').toLowerCase();if(last&&last!=='index.html')return;if(!document.querySelector('link[data-bingo-home-upgrade]')){const link=document.createElement('link');link.rel='stylesheet';link.href='bingo-home-upgrade.css?v=20260819-4';link.setAttribute('data-bingo-home-upgrade','1');document.head.appendChild(link)}if(!document.querySelector('link[data-bingo-home-responsive-final]')){const rf=document.createElement('link');rf.rel='stylesheet';rf.href='home-responsive-final.css?v=20260819-1';rf.setAttribute('data-bingo-home-responsive-final','1');document.head.appendChild(rf)}if(!document.querySelector('script[data-bingo-home-upgrade]')){const s=document.createElement('script');s.src='bingo-home-upgrade.js?v=20260819-5';s.defer=true;s.setAttribute('data-bingo-home-upgrade','1');document.head.appendChild(s)}if(!document.querySelector('link[data-bingo-featured-offers]')){const f=document.createElement('link');f.rel='stylesheet';f.href='featured-offers.css?v=20260819-1';f.setAttribute('data-bingo-featured-offers','1');document.head.appendChild(f)}if(!document.querySelector('script[data-bingo-featured-offers]')){const fs=document.createElement('script');fs.src='featured-offers.js?v=20260819-1';fs.defer=true;fs.setAttribute('data-bingo-featured-offers','1');document.head.appendChild(fs)}})();
  (function loadAddListingUpgrade(){const last=(location.pathname.split('/').pop()||'').toLowerCase();if(last!=='add-listing.html')return;if(!document.querySelector('link[data-bingo-add-listing-upgrade]')){const l=document.createElement('link');l.rel='stylesheet';l.href='add-listing-upgrade.css?v=20260819-2';l.setAttribute('data-bingo-add-listing-upgrade','1');document.head.appendChild(l)}if(!document.querySelector('script[data-bingo-add-listing-upgrade]')){const s=document.createElement('script');s.src='add-listing-upgrade.js?v=20260819-2';s.defer=true;s.setAttribute('data-bingo-add-listing-upgrade','1');document.head.appendChild(s)}})();
  (function loadMarketplaceUpgrade(){const last=(location.pathname.split('/').pop()||'').toLowerCase();if(last!=='marketplace.html')return;if(document.querySelector('link[data-bingo-marketplace-upgrade]'))return;const link=document.createElement('link');link.rel='stylesheet';link.href='marketplace-upgrade.css?v=20260819-2';link.setAttribute('data-bingo-marketplace-upgrade','1');document.head.appendChild(link)})();
  (function loadAccountMessagesUpgrade(){const last=(location.pathname.split('/').pop()||'').toLowerCase();if(last!=='dashboard.html'&&last!=='messages.html')return;if(document.querySelector('link[data-bingo-account-messages-upgrade]'))return;const link=document.createElement('link');link.rel='stylesheet';link.href='account-messages-upgrade.css?v=20260819-1';link.setAttribute('data-bingo-account-messages-upgrade','1');document.head.appendChild(link)})();
  (function loadPlaceHeroImages(){const last=(location.pathname.split('/').pop()||'').toLowerCase();if(last!=='place.html')return;if(document.querySelector('script[data-bingo-place-hero-images]'))return;const script=document.createElement('script');script.src='place-hero-images.js?v=20260819-1';script.async=false;script.setAttribute('data-bingo-place-hero-images','1');document.head.appendChild(script)})();
  if(location.pathname.endsWith('/admin.html'))return;
  let items=[],index=0,timer=null;
  function esc(s){return String(s??'').replace(/[&<>\'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt',"'":'&#39;','\"':'&quot;'}[c]));}
  function resolveMediaUrl(value){const raw=String(value||'').trim();if(!raw)return'';if(/^https?:\/\//i.test(raw)||/^data:/i.test(raw)||raw.startsWith('blob:'))return raw;try{if(window.sb&&window.sb.storage&&window.sb.storage.from){const path=raw.replace(/^\/+/, '').replace(/^bingo-banners\//,'');const {data}=window.sb.storage.from('bingo-banners').getPublicUrl(path);if(data&&data.publicUrl)return data.publicUrl}}catch(e){console.warn('BINGO banner URL:',e)}return raw}
  function mount(){if(document.getElementById('bingoGlobalBannerWrap'))return document.getElementById('bingoGlobalBanner');const wrap=document.createElement('section');wrap.id='bingoGlobalBannerWrap';wrap.className='bingo-global-banner-wrap';wrap.setAttribute('aria-label','BINGO Oman advertisement');wrap.innerHTML='<div id="bingoGlobalBanner" class="bingo-global-banner"></div>';const header=document.querySelector('header');if(header)header.insertAdjacentElement('afterend',wrap);else document.body.insertAdjacentElement('afterbegin',wrap);return document.getElementById('bingoGlobalBanner')}
  function render(){const box=mount();clearInterval(timer);if(!items.length){box.innerHTML='';return}const a=items[index%items.length],url=resolveMediaUrl(a.media_url);if(!url){box.innerHTML='';return}const media=a.media_type==='video'?'<video class="bingo-global-media" src="'+esc(url)+'" autoplay muted loop playsinline preload="auto"></video>':'<img class="bingo-global-media" src="'+esc(url)+'" alt="" loading="eager" decoding="async">';const inner=a.link_url?'<a class="bingo-global-link" href="'+esc(a.link_url)+'" target="_blank" rel="noopener noreferrer" aria-label="Advertisement">'+media+'</a>':media;box.innerHTML='<div class="bingo-global-slide active">'+inner+'</div>';if(items.length>1)timer=setInterval(()=>{index=(index+1)%items.length;render()},6000);const video=box.querySelector('video');if(video){video.muted=true;video.play().catch(()=>{})}}
  async function load(){mount();if(!window.sb||!window.sb.from)return;try{const {data,error}=await window.sb.from('site_banners').select('id,media_type,media_url,link_url,sort_order,created_at,starts_at,ends_at,status').eq('status','published').order('sort_order',{ascending:true}).order('created_at',{ascending:false});if(error)throw error;const now=Date.now();items=(data||[]).filter(a=>{const start=a.starts_at?new Date(a.starts_at).getTime():-Infinity,end=a.ends_at?new Date(a.ends_at).getTime():Infinity;return start<=now&&now<=end&&a.media_url});render()}catch(e){console.warn('BINGO global banners:',e)}}
  function init(){mount();load()}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();