(function(){'use strict';
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
let currentUser=null,currentWrap=null,channel=null,pollTimer=null,loading=false;
async function init(){if(!window.BingoAuth||!window.sb)return;const user=await BingoAuth.getUser();if(!user)return;const actions=document.querySelector('.header .actions')||document.querySelector('.actions');if(!actions||document.querySelector('.bingo-notify'))return;currentUser=user;const wrap=document.createElement('div');currentWrap=wrap;wrap.className='bingo-notify';wrap.innerHTML='<button class="bingo-notify-btn" type="button" aria-label="Notifications">🔔<span class="bingo-notify-badge"></span></button><div class="bingo-notify-panel"><div class="bingo-notify-head"><strong>Notifications</strong><button class="bingo-notify-readall" type="button" style="border:0;background:none;color:#092a82;font-size:10px;font-weight:800;cursor:pointer">Mark all read</button></div><div class="bingo-notify-list"><div class="bingo-notify-empty">Loading…</div></div></div>';actions.prepend(wrap);const btn=wrap.querySelector('.bingo-notify-btn');btn.onclick=e=>{e.stopPropagation();wrap.classList.toggle('open');if(wrap.classList.contains('open'))load(user.id,wrap)};wrap.querySelector('.bingo-notify-readall').onclick=async e=>{e.stopPropagation();await sb.rpc('user_notifications_mark_read',{p_id:null});await load(user.id,wrap)};document.addEventListener('click',e=>{if(!wrap.contains(e.target))wrap.classList.remove('open')});await load(user.id,wrap);try{channel=sb.channel('bingo-user-notifications-'+user.id).on('postgres_changes',{event:'*',schema:'public',table:'user_notifications',filter:'user_id=eq.'+user.id},()=>load(user.id,wrap)).subscribe()}catch(e){console.warn('notification realtime',e)};startPolling()}
function startPolling(){stopPolling();pollTimer=setInterval(()=>{if(document.visibilityState==='visible'&&currentUser&&currentWrap)load(currentUser.id,currentWrap)},60000)}
function stopPolling(){if(pollTimer){clearInterval(pollTimer);pollTimer=null}}
async function load(userId,wrap){if(loading||!wrap?.isConnected)return;loading=true;const list=wrap.querySelector('.bingo-notify-list'),badge=wrap.querySelector('.bingo-notify-badge');let items=[];try{
  const {data:delivery,error:deliveryError}=await sb.from('user_notifications').select('id,type,title,body,href,is_read,created_at').eq('user_id',userId).order('created_at',{ascending:false}).limit(25);if(!deliveryError)(delivery||[]).forEach(n=>items.push({id:n.id,icon:n.type?.includes('driver')?'🛵':n.type?.includes('seller')?'🏪':'📦',title:n.title,text:n.body||'',href:n.href||'orders.html',date:n.created_at,unread:!n.is_read,delivery:true}));
  const {data:convs}=await sb.from('conversations').select('id').or(`buyer_id.eq.${userId},seller_id.eq.${userId}`);const ids=(convs||[]).map(x=>x.id);if(ids.length){const {data:msgs}=await sb.from('messages').select('id,conversation_id,message,created_at,sender_id,is_read').in('conversation_id',ids).eq('is_read',false).neq('sender_id',userId).order('created_at',{ascending:false}).limit(8);(msgs||[]).forEach(m=>items.push({icon:'💬',title:'New message',text:m.message||'You have a new message',href:'messages.html?conversation='+encodeURIComponent(m.conversation_id),date:m.created_at,unread:true}))}
  items.sort((a,b)=>new Date(b.date)-new Date(a.date));const unread=items.filter(x=>x.unread).length;badge.textContent=unread>99?'99+':unread;badge.classList.toggle('show',unread>0);list.innerHTML=items.length?items.slice(0,20).map(x=>`<a class="bingo-notify-item${x.unread?' unread':''}" data-notify-id="${x.id||''}" href="${esc(x.href)}"><b>${x.icon} ${esc(x.title)}</b><small>${esc(x.text)}</small></a>`).join(''):'<div class="bingo-notify-empty">No new notifications.</div>';list.querySelectorAll('[data-notify-id]').forEach(a=>a.addEventListener('click',()=>{if(a.dataset.notifyId)sb.rpc('user_notifications_mark_read',{p_id:a.dataset.notifyId})}))
}catch(e){console.warn('BINGO notifications:',e);list.innerHTML='<div class="bingo-notify-empty">Notifications are temporarily unavailable.</div>'}finally{loading=false}}
function cleanup(){stopPolling();if(channel){try{sb.removeChannel(channel)}catch(e){}channel=null}}
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&currentUser&&currentWrap)load(currentUser.id,currentWrap)});window.addEventListener('pagehide',cleanup,{once:true});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();})();
