-- =========================================================
-- BINGO Oman - SAFE FULL DELIVERY RESET (TEST ENVIRONMENT)
-- Date: 2026-08-20
--
-- PURPOSE
--   Reset ALL BINGO Delivery operational/test data while preserving:
--   * auth.users accounts (no Auth user is deleted automatically)
--   * public.profiles / BINGO core accounts
--   * Store/catalog data outside the Delivery module
--   * Delivery schema/functions/pricing/zones
--
-- WHY AUTH USERS ARE NOT AUTO-DELETED
--   A Delivery driver/seller may also be a real BINGO account. SQL cannot safely
--   infer which Auth accounts are disposable. This script records the candidate
--   Driver/Seller Auth users before removing their Delivery profiles, then prints
--   them at the end for a deliberate Auth cleanup step.
-- =========================================================

begin;

-- 1) Snapshot Delivery-linked Auth accounts BEFORE reset.
drop table if exists pg_temp.bingo_delivery_auth_candidates;
create temporary table bingo_delivery_auth_candidates on commit preserve rows as
select distinct
  u.id as user_id,
  u.email,
  case
    when d.id is not null and s.owner_id is not null then 'driver+seller'
    when d.id is not null then 'driver'
    when s.owner_id is not null then 'seller'
    else 'delivery'
  end as delivery_role,
  p.role as bingo_profile_role
from auth.users u
left join public.delivery_drivers d on d.id=u.id
left join public.delivery_stores s on s.owner_id=u.id
left join public.profiles p on p.id=u.id
where d.id is not null or s.owner_id is not null;

-- 2) Reset loyalty / points generated by Delivery.
do $$
begin
  if to_regclass('public.bingo_points_ledger') is not null then
    execute 'delete from public.bingo_points_ledger where order_id is not null or role = ''driver''';
  end if;
end $$;

-- 3) Reset optional Delivery reward/notification tables if installed.
do $$
begin
  if to_regclass('public.delivery_driver_notifications') is not null then
    execute 'truncate table public.delivery_driver_notifications restart identity cascade';
  end if;
  if to_regclass('public.delivery_driver_rewards') is not null then
    execute 'truncate table public.delivery_driver_rewards restart identity cascade';
  end if;
end $$;

-- 4) Reset all order lifecycle data.
-- Child tables first for clarity; CASCADE makes this resilient to later additions.
do $$
begin
  if to_regclass('public.delivery_order_codes') is not null then
    execute 'truncate table public.delivery_order_codes restart identity cascade';
  end if;
  if to_regclass('public.delivery_ratings') is not null then
    execute 'truncate table public.delivery_ratings restart identity cascade';
  end if;
  if to_regclass('public.delivery_complaints') is not null then
    execute 'truncate table public.delivery_complaints restart identity cascade';
  end if;
  if to_regclass('public.delivery_earnings') is not null then
    execute 'truncate table public.delivery_earnings restart identity cascade';
  end if;
  if to_regclass('public.delivery_assignments') is not null then
    execute 'truncate table public.delivery_assignments restart identity cascade';
  end if;
  if to_regclass('public.delivery_order_items') is not null then
    execute 'truncate table public.delivery_order_items restart identity cascade';
  end if;
  if to_regclass('public.delivery_orders') is not null then
    execute 'truncate table public.delivery_orders restart identity cascade';
  end if;
end $$;

-- 5) Reset live driver state and remove ALL Delivery driver profiles.
do $$
begin
  if to_regclass('public.delivery_driver_locations') is not null then
    execute 'truncate table public.delivery_driver_locations restart identity cascade';
  end if;
  if to_regclass('public.delivery_drivers') is not null then
    execute 'truncate table public.delivery_drivers restart identity cascade';
  end if;
end $$;

-- 6) Remove Delivery seller/store profiles.
-- This does NOT delete Store/catalog records outside public.delivery_stores.
do $$
begin
  if to_regclass('public.delivery_stores') is not null then
    execute 'truncate table public.delivery_stores restart identity cascade';
  end if;
end $$;

-- 7) Reset optional dispatch controls / per-driver settings if present.
do $$
declare
  r record;
begin
  for r in
    select schemaname, tablename
    from pg_tables
    where schemaname='public'
      and tablename in (
        'delivery_driver_capacity',
        'delivery_driver_capacities',
        'delivery_driver_priority',
        'delivery_driver_priorities',
        'delivery_dispatch_queue',
        'delivery_dispatch_state'
      )
  loop
    execute format('truncate table %I.%I restart identity cascade',r.schemaname,r.tablename);
  end loop;
end $$;

commit;

-- =========================================================
-- RESULT / VERIFICATION
-- =========================================================
select 'delivery_orders' as item, count(*)::bigint as remaining from public.delivery_orders
union all select 'delivery_drivers', count(*) from public.delivery_drivers
union all select 'delivery_stores', count(*) from public.delivery_stores
union all select 'delivery_assignments', count(*) from public.delivery_assignments
union all select 'delivery_earnings', count(*) from public.delivery_earnings
union all select 'delivery_ratings', count(*) from public.delivery_ratings
order by item;

-- These are the Auth accounts that WERE linked to Delivery before reset.
-- Review this result before deleting any user in Supabase Authentication.
select
  user_id,
  email,
  delivery_role,
  bingo_profile_role,
  case
    when bingo_profile_role='admin' then 'KEEP - ADMIN'
    else 'REVIEW FOR AUTH DELETE'
  end as recommendation
from bingo_delivery_auth_candidates
order by recommendation, email;

-- IMPORTANT:
-- Do NOT run a blanket `delete from auth.users` here.
-- Delete only the reviewed disposable Driver/Seller accounts from
-- Supabase Dashboard > Authentication > Users, or run a separate explicit
-- whitelist SQL after reviewing the result above.
